#! /usr/bin/env python3
import argparse
import collections
import itertools
import json
import os
import subprocess
import shutil
import string
import sys
import tempfile

__version__ = '0.0.2-dev3'

def classify_onz(nts, tetrad):
    distinct_chain_count = len(set([nts[i]['chain_name'] for i in tetrad]))
    classification = 'n/a'
    if distinct_chain_count == 1:
        n1 = nts[tetrad[0]]['index']
        n2 = nts[tetrad[1]]['index']
        n3 = nts[tetrad[2]]['index']
        n4 = nts[tetrad[3]]['index']
        if n2 < n3 and n3 < n4:
            classification = 'O+'
        elif n2 > n3 and n3 > n4:
            classification = 'O-'
        elif n2 < n3 and n2 < n4:
            classification = 'N+'
        elif n2 < n3 and n2 > n4:
            classification = 'N-'
        elif n2 > n3 and n2 < n4:
            classification = 'Z+'
        elif n2 > n3 and n2 > n4:
            classification = 'Z-'
    return classification

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--json', action='store_true', help='parse input file from JSON format')
    parser.add_argument('--stacking-mismatch', help='a perfect tetrad stacking covers 4 nucleotides; this option can be used with value 1 or 2 to allow this number of nucleotides to be non-stacked with otherwise well aligned tetrad [default=2]', default=2)
    parser.add_argument('--relaxed-stem-definition', action='store_true', help='when set, two sequentially close tetrades will be considered a stem regardless of their stacking')
    parser.add_argument('--strict', action='store_true', help='nucleotides in tetrad are found when linked only by cWH pairing')
    parser.add_argument('--version', action='version', version='%(prog)s {}'.format(__version__))
    parser.add_argument('input', help='a JSON file produced by DSSR if "--json" is used, otherwise a PDB or PDBx/MMCIF file to be analyzed first by DSSR')
    args = parser.parse_args()

    stacking_mismatch = int(args.stacking_mismatch)

    if args.json:
        with open(args.input) as jsonfile:
            dssr = jsonfile.read()
    else:
        currdir = os.path.dirname(os.path.realpath(__file__))
        tempdir = tempfile.mkdtemp()
        shutil.copy(os.path.join(currdir, 'x3dna-dssr'), tempdir)
        shutil.copy(args.input, tempdir)
        dssr = subprocess.Popen(['./x3dna-dssr', '-i={}'.format(os.path.basename(args.input)), '--json', '--symmetry'], stdout=subprocess.PIPE, stderr=subprocess.PIPE, cwd=tempdir)
        dssr, _ = dssr.communicate()
        shutil.rmtree(tempdir)

    try:
        data = json.loads(dssr)
    except:
        print('Invalid JSON in', args.input, file=sys.stderr)
        exit(1)

    if 'pairs' not in data:
        print('None')
        exit()

    nts = dict()
    for nt in data['nts']:
        nt_id = nt['nt_id']
        if nt_id.find(':') != -1:
            nt['chain_name'] = '{}:{}'.format(nt_id.split(':')[0], nt['chain_name'])
        nts[nt_id] = nt

    stacks = list()
    for stack in data['stacks']:
        stacks.append(stack['nts_long'].split(','))

    cwh = dict()
    for pair in data['pairs']:
        lw = pair['LW']
        nt1 = nts[pair['nt1']]['nt_id']
        nt2 = nts[pair['nt2']]['nt_id']
        if lw == 'cWH':
            if nt1 not in cwh:
                cwh[nt1] = list()
            cwh[nt1].append(nt2)

    for pair in data['pairs']:
        lw = pair['LW']
        nt1 = nts[pair['nt1']]['nt_id']
        nt2 = nts[pair['nt2']]['nt_id']
        if lw == 'cHW':
            if nt2 not in cwh:
                cwh[nt2] = list()
            cwh[nt2].append(nt1)

    if not args.strict:
        for pair in data['pairs']:
            lw = pair['LW']
            nt1 = nts[pair['nt1']]['nt_id']
            nt2 = nts[pair['nt2']]['nt_id']
            if nt1 not in cwh:
                cwh[nt1] = list()
            cwh[nt1].append(nt2)
            if nt2 not in cwh:
                cwh[nt2] = list()
            cwh[nt2].append(nt1)

    # search for a tetrad: i -> j -> k -> l -> i
    used = set()
    tetrads = list()
    for i in cwh:
        for j in [j for j in cwh[i] if j in cwh and j not in (i)]:
            for k in [k for k in cwh[j] if k in cwh and k not in (i, j)]:
                for l in [l for l in cwh[k] if l in cwh and l not in (i, j, k) and i in cwh[l]]:
                    if any([i in used, j in used, k in used, l in used]):
                        continue
                    ni, nj, nk, nl = nts[i]['index'], nts[j]['index'], nts[k]['index'], nts[l]['index']
                    nmin = min(ni, nj, nk, nl)
                    if ni == nmin:
                        tetrad = (i, j, k, l)
                    elif nj == nmin:
                        tetrad = (j, k, l, i)
                    elif nk == nmin:
                        tetrad = (k, l, i, j)
                    else:
                        tetrad = (l, i, j, k)
                    tetrads.append(tetrad)
                    used.update(tetrad)

    def check_tetrads_stem(ti, tj):
        ti = [nts[nt]['index'] for nt in ti]
        tj = [nts[nt]['index'] for nt in tj]
        index_diff = [j - i for i, j in zip(ti, tj)]
        return all([abs(diff) == 1 for diff in index_diff])

    stems = dict()
    for ti, tj in itertools.combinations(tetrads, 2):
        if check_tetrads_stem(ti, tj):
            if not ti in stems:
                stems[ti] = list()
            stems[ti].append(tj)
            if not tj in stems:
                stems[tj] = list()
            stems[tj].append(ti)

    def check_tetrads_stacking(ti, tj):
        ti, tj = set(ti), set(tj)
        for stack in stacks:
            stack = set(stack)
            if not stack.isdisjoint(ti) and not stack.isdisjoint(tj):
                ti.difference_update(stack)
                tj.difference_update(stack)
        return len(ti) <= stacking_mismatch and len(tj) <= stacking_mismatch

    stackings = dict()
    for ti, tj in itertools.combinations(tetrads, 2):
        if check_tetrads_stacking(ti, tj):
            if not ti in stackings:
                stackings[ti] = list()
            stackings[ti].append(tj)
            if not tj in stackings:
                stackings[tj] = list()
            stackings[tj].append(ti)

    quadruplexes = list()
    candidates = set(tetrads)
    while candidates:
        quadruplex = [candidates.pop()]
        changed = True
        while changed:
            changed = False
            for tetrad in quadruplex:
                if tetrad in stackings:
                    for stacked in stackings[tetrad]:
                        if stacked in candidates:
                            quadruplex.append(stacked)
                            candidates.remove(stacked)
                            changed = True
                if args.relaxed_stem_definition and tetrad in stems:
                    for stemmed in stems[tetrad]:
                        if stemmed in candidates:
                            quadruplex.append(stemmed)
                            candidates.remove(stemmed)
                            changed = True
        quadruplexes.append(quadruplex)

    if len(quadruplexes) == 0:
        print('None')
        exit()

    quadruplexes.sort(key=lambda x: len(x), reverse=True)

    for quadruplex in quadruplexes:
        if len(quadruplex) > 1:
            print('n4-helix with {} tetrads'.format(len(quadruplex)))
        else:
            print('single tetrad without stacking')

        quadruplex = list(quadruplex)
        quadruplex.sort(key=lambda x: nts[x[0]]['index'])

        previous_chains = None
        previous = []
        classified = []
        direction = 'n/a'
        votes_direction = {'parallel': 0, 'antiparallel': 0, 'hybrid' : 0}
        votes_classification = {'O' : 0, 'N' : 0, 'Z' : 0, 'n/a' : 0}

        for tetrad in quadruplex:
            current_chains = collections.Counter([nts[nt]['chain_name'] for nt in tetrad])
            current = [nts[nt]['index'] for nt in tetrad]
            if previous:
                index_diff = [j - i for i, j in zip(sorted(previous), sorted(current))]
                is_stem = previous_chains == current_chains
                is_parallel = len(set(index_diff) - {1, 2, 3}) == 0 or len(set(index_diff) - {-1, -2, -3}) == 0
                is_antiparallel = not is_parallel \
                        and len(set(index_diff) - {1, -1, 2, -2, 3, -3}) == 0 \
                        and collections.Counter([1 if i > 0 else -1 for i in index_diff]).most_common()[0][1] == 2
                if is_stem:
                    direction = 'parallel' if is_parallel else 'antiparallel' if is_antiparallel else 'hybrid'
                    votes_direction[direction] += 1
                if not is_stem:
                    if len(classified) == 1:
                        print('  single tetrad')
                    else:
                        votes_direction = sorted(votes_direction.items(), key=lambda x: x[1], reverse=True)
                        # clear winner
                        if votes_direction[1][1] == 0:
                            stem_type = votes_direction[0][0]
                        else:
                            stem_type = 'hybrid'

                        votes_classification = sorted(votes_classification.items(), key=lambda x: x[1], reverse=True)
                        # clear winner
                        if votes_classification[1][1] == 0:
                            classification_type = votes_classification[0][0]
                        else:
                            classification_type = 'M' # Mixed
                        if classification_type == 'n/a':
                            classification_type = 'U' # Unknown

                        print('  {}{} quadruplex with {} tetrads'.format(classification_type[0], stem_type[0], len(classified)))
                    print('\n'.join(classified))
                    classified = []
                    votes_direction = {'parallel': 0, 'antiparallel': 0, 'hybrid' : 0}
                    votes_classification = {'O' : 0, 'N' : 0, 'Z' : 0, 'n/a' : 0}
            previous_chains = current_chains
            previous = current

            classification = classify_onz(nts, tetrad)
            votes_classification[classification.replace('-', '').replace('+', '')] += 1
            classified.append('    {} {} {} {} {} {}'.format(tetrad[0], tetrad[1], tetrad[2], tetrad[3], direction, classification))

        if len(classified) == 1:
            print('  single tetrad')
        else:
            votes_direction = sorted(votes_direction.items(), key=lambda x: x[1], reverse=True)
            # clear winner
            if votes_direction[1][1] == 0:
                stem_type = votes_direction[0][0]
            else:
                stem_type = 'hybrid'

            votes_classification = sorted(votes_classification.items(), key=lambda x: x[1], reverse=True)
            # clear winner
            if votes_classification[1][1] == 0:
                classification_type = votes_classification[0][0]
            else:
                classification_type = 'M' # Mixed
            if classification_type == 'n/a':
                classification_type = 'U' # Unknown

            print('  {}{} quadruplex with {} tetrads'.format(classification_type[0], stem_type[0], len(classified)))
        print('\n'.join(classified))

    layer1 = list()
    layer2 = list()
    for quadruplex in quadruplexes:
        for tetrad in quadruplex:
            tetrad = tuple(map(lambda nt: nts[nt]['index'], tetrad))
            layer1.append(sorted([tetrad[0], tetrad[1]]))
            layer1.append(sorted([tetrad[2], tetrad[3]]))
            layer2.append(sorted([tetrad[0], tetrad[3]]))
            layer2.append(sorted([tetrad[1], tetrad[2]]))

    brackets = ('([{<' + string.ascii_uppercase, ')]}>' + string.ascii_lowercase)

    def fcfs(pairs):
        pairs = sorted(pairs, key=lambda x: x[1])
        print(pairs)
        order = dict()
        for i in range(len(pairs)):
            xi, yi = pairs[i][0], pairs[i][1]
            conflicts = 0
            for j in range(i):
                xj, yj = pairs[j][0], pairs[j][1]
                if (xi < xj < yi < yj) or (xj < xi < yj < yi):
                    conflicts = max(conflicts, order[xj][0] + 1)
            order[xi] = conflicts, brackets[0][conflicts]
            order[yi] = conflicts, brackets[1][conflicts]
        return order

    layer1 = fcfs(layer1)
    layer2 = fcfs(layer2)
    sequence = list()
    dbn1 = list()
    dbn2 = list()

    for nt in nts:
        index = nts[nt]['index']
        sequence.append(nts[nt]['nt_code'])
        if index in layer1:
            dbn1.append(layer1[index][1])
        else:
            dbn1.append('.')
        if index in layer2:
            dbn2.append(layer2[index][1])
        else:
            dbn2.append('.')

    print()
    print(''.join(sequence))
    print(''.join(dbn1))
    print(''.join(dbn2))
