#! /usr/bin/env python3
import argparse
import gzip
import json
import os
import shutil
import subprocess
import sys
import tempfile

from collections import defaultdict

__version__ = '1.0.0'


class Pair:
    def __init__(self, nt1, nt2):
        self.pair = (nt1, nt2)

    def reverse(self):
        return Pair(self.pair[1], self.pair[0])


class Structure:
    def __init__(self, data: dict):
        self.pairs = self._read_pairs(data)
        self.graph = dict()

    def build_graph(self):
        graph = defaultdict(list)
        for pair in self.pairs.values():
            nt1, nt2 = pair.pair
            graph[nt1].append(nt2)
        self.graph = graph

    def has_tetrad(self):
        for i in self.graph:
            for j in filter(lambda x: x != i, self.graph[i]):
                for k in filter(lambda x: x not in (i, j), self.graph[j]):
                    for l in filter(lambda x: x not in (i, j, k) and x in self.graph[i], self.graph[k]):
                        return True

    def _read_pairs(self, data: dict):
        pairs = dict()
        for pair in data['pairs']:
            nt1, nt2 = pair['nt1'], pair['nt2']
            pair = Pair(nt1, nt2)
            pairs[(nt1, nt2)] = pair
            pairs[(nt2, nt1)] = pair.reverse()
        return pairs


def parse_arguments():
    parser = argparse.ArgumentParser()
    parser.add_argument('--json', action='store_true', help='parse input file from JSON format')
    parser.add_argument('--version', action='version', version='%(prog)s {}'.format(__version__))
    parser.add_argument('input',
                        help='a JSON file produced by DSSR if "--json" is used, otherwise a PDB or PDBx/MMCIF file to '
                             'be analyzed first by DSSR')
    return parser.parse_args()


def load_dssr_results(args):
    is_gzip = os.path.splitext(args.input)[1] == '.gz'

    if args.json:
        open_proxy = gzip.open if is_gzip else open
        with open_proxy(args.input) as jsonfile:
            dssr = jsonfile.read()
    else:
        tempdir = tempfile.mkdtemp()

        if is_gzip:
            fd, inputfile = tempfile.mkstemp(dir=tempdir)
            os.close(fd)
            with gzip.open(args.input) as compressed:
                with open(inputfile, 'wb') as uncompressed:
                    shutil.copyfileobj(compressed, uncompressed)
        else:
            inputfile = args.input

        currdir = os.path.dirname(os.path.realpath(__file__))
        shutil.copy(os.path.join(currdir, 'x3dna-dssr'), tempdir)
        dssr = subprocess.Popen(
            ['./x3dna-dssr', '-i={}'.format(os.path.abspath(inputfile)), '--json'],
            stdout=subprocess.PIPE, stderr=subprocess.PIPE, cwd=tempdir)
        dssr, _ = dssr.communicate()

        shutil.rmtree(tempdir)

    try:
        return json.loads(dssr)
    except json.JSONDecodeError:
        print('Invalid JSON in', args.input, file=sys.stderr)
        exit(1)


if __name__ == '__main__':
    args = parse_arguments()
    dssr = load_dssr_results(args)

    if 'pairs' not in dssr:
        exit(1)

    structure = Structure(dssr)
    structure.build_graph()

    if structure.has_tetrad():
        exit()
    else:
        exit(1)
